# Generated by Django 5.0 on 2023-12-14 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_blocklist_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='user_profile.profile'),
        ),
    ]
